import os
TELEGRAM_PERSONAL_CHAT_ID = os.environ.get("TELEGRAM_PERSONAL_CHAT_ID")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHANNEL_ID = os.environ.get("TELEGRAM_CHANNEL_ID")

SYMBOLS = ["BTC/USDT"]

TIMEFRAME = "1h"
CANDLE_LIMIT = 250

POSITION_CHECK_TIMEFRAME = "1m"

EMA_FAST = 50
EMA_SLOW = 200
RSI_PERIOD = 14
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
VOLUME_MA_PERIOD = 20
VOLUME_MULTIPLIER = 1.5

ATR_PERIOD = 14
ATR_SL_MULTIPLIER = 1.5
MIN_SL_PERCENT = 0.0015
MAX_SL_PERCENT = 0.015

TP1_R = 1.0
TP2_R = 2.0
TP3_R = 3.0

RISK_DOLLARS_BY_LEVEL = {
    "A+": 7,
    "A": 6,
    "B": 5,
}

LEVEL_LABELS = {
    4: "A+",
    3: "A",
    2: "B",
}
MIN_CONDITIONS_TO_SIGNAL = 2

MOVE_SL_TO_BREAKEVEN_AFTER_TP2 = True

# Codenames tagging which strategy sent a signal, without revealing the mechanism
STRATEGY_NAME_PRIMARY = "Orion"   # the existing tiered indicator strategy
STRATEGY_NAME_ENGULF = "Nova"     # the new prominence-engulfing strategy

# Nova (engulfing) parameters — backtested at prominence 1000
ENGULF_PROMINENCE_THRESHOLD = 1000
ENGULF_MIN_ENGULF_RATIO = 1.0
ENGULF_LOT_SIZE = 0.01
ENGULF_SL_DOLLARS = 5
ENGULF_TP1_DOLLARS = 5
ENGULF_TP2_DOLLARS = 10
ENGULF_TP3_DOLLARS = 15

POSITION_EXPIRY_HOURS = 48
